# Generated by Django 3.1.2 on 2020-11-07 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('period', models.IntegerField(choices=[(365, 'Daily'), (12, 'Monthly'), (1, 'Yearly')], default=365)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='DateValueGoal',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('goal_amount', models.FloatField(default=0.0)),
                ('by_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValueBridge',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('activates_at', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('as_percentage', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('repeat_n', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(choices=[('SS', 'Start'), ('DD', 'Daily'), ('ND', 'NDaily'), ('WW', 'Weekly'), ('BW', 'BiWeekly'), ('MM', 'Monthly'), ('NM', 'NMonthly'), ('YY', 'Yearly'), ('NY', 'NYearly'), ('EE', 'End')], default='SS', max_length=2)),
                ('apr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.apr')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
            ],
            options={
                'ordering': ['created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DateValueGoalVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_range', models.FloatField(default=0.0)),
                ('bottom_range', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.datevaluegoal')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateValueGoalConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_range', models.FloatField(default=0.0)),
                ('bottom_range', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.datevaluegoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateBridge',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('activates_on', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='apr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.apr'),
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.plan'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
