# Generated by Django 3.0.4 on 2020-10-10 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('period', models.IntegerField(choices=[(365, 'Daily'), (12, 'Monthly'), (1, 'Yearly')], default=365)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
