# Generated by Django 3.1.2 on 2020-10-16 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['created', 'name']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='apr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.apr'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='apr',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_account', models.CharField(default='', max_length=255)),
                ('from_account', models.CharField(default='', max_length=255)),
                ('repeat_n', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval', models.CharField(choices=[('OO', 'Once'), ('DD', 'Daily'), ('ND', 'NDaily'), ('WW', 'Weekly'), ('BW', 'BiWeekly'), ('MM', 'Monthly'), ('NM', 'NMonthly'), ('YY', 'Yearly'), ('NY', 'NYearly')], default='DD', max_length=2)),
                ('apr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.apr')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
            ],
            options={
                'ordering': ['created', 'name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.plan'),
        ),
    ]
