# Generated by Django 3.1.2 on 2020-10-17 00:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201016_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateValueGoal',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('min_amount', models.FloatField(default=0.0)),
                ('by_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='as_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='apr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.apr'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='interval',
            field=models.CharField(choices=[('SS', 'Start'), ('DD', 'Daily'), ('ND', 'NDaily'), ('WW', 'Weekly'), ('BW', 'BiWeekly'), ('MM', 'Monthly'), ('NM', 'NMonthly'), ('YY', 'Yearly'), ('NY', 'NYearly'), ('EE', 'End')], default='SS', max_length=2),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.CreateModel(
            name='ValueBridge',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('activates_at', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
            ],
        ),
        migrations.CreateModel(
            name='DateValueGoalVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_range', models.FloatField(default=0.0)),
                ('bottom_range', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datevaluegoal')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='DateBridge',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('activates_on', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.plan')),
            ],
        ),
    ]
